### ISSUE TITLE
Is this for PUBLIC comments ? How to enable ?

### ISSUE THREAD

**Issue by sylvaticus** [aleen42/gitbook-comments#7]
Hello, sorry to bother you... I have a [Julia tutorial](https://syl1.gitbook.io/julia-language-a-concise-tutorial/) on gitbook.com and I would like to add PUBLIC comments to it.
Is this plugin for that ? How do I enable it ?
Thanks for your kind reply !

Antonello

**Comment by aleen42** [comment]
@sylvaticus this plugin should be used by integrating with GitHub, or GitLab. It means that only authorized users can leave a comment because comments are only stored in the system. Besides, the plugin is only tested under Gitbook 3.2.2, if you want to try, take [my wiki](https://github.com/aleen42/PersonalWiki) as an example.

**Comment by sylvaticus** [comment]
Thank you for your kind reply...
